version: "3"
services:
  web:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - pgdata

volumes:
  pgdata:
